### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by yuanjie000** [asiekierka/UnlimitedChiselWorks#1]
**Add this mod to AoE modpack version(1.1.1c)**
![qq 20170918112159](https://user-images.githubusercontent.com/20902900/30528307-66dd1238-9c64-11e7-9e6e-3531a41f4e75.png)

**Comment by asiekierka** [comment]
Minecraft version?

**Comment by asiekierka** [comment]
Works fine for me; are you using OptiFine or any additional mods?

**Comment by yuanjie000** [comment]
Haven't use optfine at all.
Add some Decorative mod : BiblioCraft and ExtraBitManipulation and so on

**Comment by asiekierka** [comment]
As I said, I created my own MultiMC instance and it works perfectly fine. Could you try with AoE 1.1.1c and UCW alone, no other changes?

**Comment by yuanjie000** [comment]
I will have a try

**Comment by yuanjie000** [comment]
In this case, everything is fine, and now I am looking for which mod is causing this problem

**Comment by yuanjie000** [comment]
Finally , i find it. this problem was caused by _liteloader-snapshot-b11_ !

**Comment by asiekierka** [comment]
This will probably not be fixed, as it works fine on 1.12 and the part of code LiteLoader breaks is already far too hacky to have an excuse to exist. Sorry.

**Comment by asiekierka** [comment]
(It also works fine on 1.11.2, so most likely a LiteLoader bug?)
