### ISSUE TITLE
Unable to acquire most blocks using Chisel chisels on 1.12.2 server

### ISSUE THREAD

**Issue by PieExplosion** [asiekierka/UnlimitedChiselWorks#12]
Using a Chisel chisel, unable to chisel blocks to most UCW variants on Multiplayer servers.  All available variants show as normal when inserted/selected with chisel.  Some of them allow the first, two, or four variants to be pulled/chiseled, but none beyond that.  "iChisel" will deceptively chisel the block item, but server will revert it.  Blocks can be pulled from creative-esque menus and placed just fine.  Everything works 100% fine in Single Player.

Client Minecraft version 1.12.2 using:
_MultiMC 0.6.0-develop-1082
Forge 14.23.0.2491
LWJGL 2.9.1_

Server running Forge 14.23.0.2491 using installer jar.

Mods files running on both using default config files:
_Chisel-MC1.12-0.0.14.18
CTM-MC1.12-0.2.3.9
UnlimitedChiselWorks-0.1.5_

Tested with blocks from each of these mods one-by-one with fresh configs and worlds:
_ImmersiveEngineering-0.12-72
Traverse-1.12.1-1.3.1
AbyssalCraft-1.12-1.9.4-pre-4_

Initially ran into this issue on a private modpack being hosted on a friend's server.  Hosted a server locally in attempt to narrow down issues.  I apologize in advance if there was some sort of formatting that I should be using for this issue report.

**Comment by MushroomDynamo** [comment]
I am commenting to show interest in this issue; I am able to replicate it with a similar configuration (Immersive Engineering 0.12-74, Forge #2517, UCW 0.15). The mod is essentially nonfunctional on 1.12 servers.

**Comment by asiekierka** [comment]
This is actually a bug in Chisel, as their getSubBlocks() is client-side-only.

Paging @tterrag1098 - could you please fix it in your 1.12 branch and push a new version?

**Comment by tterrag1098** [comment]
This has been fixed, it will be included in the next release.

**Comment by asiekierka** [comment]
Worked around locally so you don't have to wait!

https://github.com/asiekierka/UnlimitedChiselWorks/commit/4da69eb15bbf5f211a69753f822b31145c8ea4ce
