### ISSUE TITLE
Regarding Covens, and dealing with future support

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/UnlimitedChiselWorks#15]
Covens and Witchworks have merged, and are still in the process of getting everything aligned and what not. I would advise building against the merger, Bewitchment (https://github.com/Um-Mitternacht/Bewitchment), when the changes are fully through, since you seem to have set up support for Covens in the past. So far, the planks have yet to make it fully to the merger, as Zabi is rather busy with his side of things.

**Comment by asiekierka** [comment]
Bewitchment has been supported for quite a while, so I guess this can be closed. (The Covens JSON is kept, as it does not hurt)
