### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by saphsara** [asiekierka/UnlimitedChiselWorks#17]
![screenshot 4](https://user-images.githubusercontent.com/33788318/35166002-62c36e3e-fd1e-11e7-80cb-318f2c1ff252.png)
![screenshot 5](https://user-images.githubusercontent.com/33788318/35166003-62d74468-fd1e-11e7-97c1-d0983ecf00ce.png)

**Comment by asiekierka** [comment]
What version of both mods?

**Comment by saphsara** [comment]
UnlimitedChiselWorks-0.1.9
UnlimitedChiselWorks-Botany-0.1.1

**Comment by saphsara** [comment]
oh is there a way i can make mod work with the blocks in silent gem mod?

**Comment by asiekierka** [comment]
1. What modpack are you using? This definitely looks strange. Oh, right - you need a relatively recent version of Forge; 2571+ is necessary for the colors to work.
2. You could write your own JSONs (see assets/unlimitedchiselworks/ucwdefs for examples), or I can look into it myself.

**Comment by asiekierka** [comment]
Nevermind, I found the issue.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/UnlimitedChiselWorks/commit/2fbccf5ceb86cff74c51fb93ee732d9bea46cd90

**Comment by saphsara** [comment]
1.   What modpack are you using? This definitely looks strange. Oh, right - you need a relatively recent version of Forge; 2571+ is necessary for the colors to work. **I am using the lastest forge. it is a modpack i put together.** 

2.    You could write your own JSONs (see assets/unlimitedchiselworks/ucwdefs for examples), or I can look into it myself.  **lol no clue how to do that... I give you alot of credit. it looks like alot of hard work. thank you for looking into this**
