### ISSUE TITLE
Colorless

### ISSUE THREAD

**Issue by saphsara** [asiekierka/UnlimitedChiselWorks#18]
I am sooooo happy.. thank you for making my day, I have the flu and so happy to see silent gems working with your mod... I am not to  worry about Binnie mod working since i got silent gems but i don't know if you fixed it because it is still colorless just wanted to let you know.. thank you again you are awesome

**Comment by asiekierka** [comment]
No need to make a new issue, I'm pretty sure I fixed it though. Update to the latest version of everything.

**Comment by saphsara** [comment]
oh ok thank you.
