### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by saphsara** [asiekierka/UnlimitedChiselWorks#19]
I love this mod soooo much thank you for all your hard work.. Have you ever thought about doing an unlimited stairs, walls and fence mod like this one?

**Comment by asiekierka** [comment]
Yes.

**Comment by saphsara** [comment]
so does that mean i might see a new mod in the upcoming future?  :)

**Comment by asiekierka** [comment]
As evident by the delay, not yet. However, I have thought about it, and it is on my TODO.

**Comment by charlesbevans** [comment]
In the meantime, you can get some with ArchitectureCraft. It's an extra step, and doesn't do every block, but it's out and it has other cool features.
