### ISSUE TITLE
[1.12.2] Model loading errors on startup

### ISSUE THREAD

**Issue by NotAVerb** [asiekierka/UnlimitedChiselWorks#21]
https://gist.github.com/NotAVerb/7e144ca357983fd7bb540f31b9d3e01d

Chisel proper isn't throwing any model loading errors.
I'm not sure if anything is actually breaking in game, but these are an extra four hundred lines that I'd rather have not be there.

Version: 0.1.10

**Comment by asiekierka** [comment]
Fixed in 0.3.1.
