### ISSUE TITLE
Crash: Running out of IDs

### ISSUE THREAD

**Issue by Xiaminou** [asiekierka/UnlimitedChiselWorks#27]
[crash-2018-03-13_16.33.22-client.txt](https://github.com/asiekierka/UnlimitedChiselWorks/files/1928108/crash-2018-03-13_16.33.22-client.txt)

I had to remove this mod because it made my modpack run out of IDs. Is there anything that could be done to reduce the number of IDs this mod (and the other unlimited chisel mods) take?

Minecraft: 1.12.2
Forge: 2641
Mods: [list.txt](https://github.com/asiekierka/UnlimitedChiselWorks/files/1928114/list.txt)

**Comment by asiekierka** [comment]
Yes, edit unlimitedchiselworks.cfg.
