### ISSUE TITLE
[1.12.2] Crash - net.minecraft.client.renderer.StitcherException:

### ISSUE THREAD

**Issue by MokahTGS** [asiekierka/UnlimitedChiselWorks#28]
Getting a crash when trying to load now.  Not sure what's going on, as this was working a day ago.  Updated some mods and now it doesn't seem to want to launch.

Crash Log: https://pastebin.com/X52Ehj2t

Mod List: https://pastebin.com/aLg4mdaJ

UnlimitedChiselWorks-0.1.11.jar
UnlimitedChiselWorks-Botany-0.1.2.jar

**Comment by asiekierka** [comment]
You have too many/too big textures and your GPU can't handle it!

You'll need to remove some mods or disable some UCW blocks or disable blocks in other mods, et cetera.
