### ISSUE TITLE
[Request] Thaumcraft support

### ISSUE THREAD

**Issue by scribbler957** [asiekierka/UnlimitedChiselWorks#40]
I'm surprised no one asked for TC5 support. Then again, the raw silverwood and greatwood planks are a bit fugly... Any chance of getting the log texture contrast for planks? Thanks

**Comment by P3rf3ctXZer0** [comment]
@scribbler957 easy because Azanor does not like making his mod work with others ... he is one of those devs that even with rock solid proof believes his mod can never have issues.

**Comment by scribbler957** [comment]
Unlike Vazkii, and RWTema, and... well, I'd say any maker of a large, popular mod is a candidate, but blay09, for one, is very open to new ideas and feedback. Even when he declines he's respectful about it.
Anyway, I'm tired of problem child mods so I'm just going to make my own packs.
I'm closing the request. Thank you.

**Comment by asiekierka** [comment]
Azanor is the creator of Thaumcraft, not Blay09.

The reason UCW has not received Thaumcraft support is because Chisel used to include official Thaumcraft support, and my assumption was that said support would be restored.

**Comment by scribbler957** [comment]
I am aware of who both are and your reasoning is fair. Thank you.
