### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Sunekaer** [asiekierka/UnlimitedChiselWorks#41]
Chisel-MC1.12.2-0.2.1.35
UCW-0.2.0
UCW Bontany-0.1.2

Crash on launch 
https://paste.feed-the-beast.com/view/b54ad76b
https://paste.feed-the-beast.com/view/c42fdd28#L830

**Comment by asiekierka** [comment]
Could not reproduce.

**Comment by Sunekaer** [comment]
ill reopen if i experience it with newer java
