### ISSUE TITLE
the pl.asie.ucw.UCWMagic was real

### ISSUE THREAD

**Issue by Yoghurt4C** [asiekierka/UnlimitedChiselWorks#46]
https://paste.dimdev.org/agamodudim.mccrash
![image](https://user-images.githubusercontent.com/11313954/59379641-cfd89d00-8d5f-11e9-8782-04832ff2cd72.png)

**Comment by asiekierka** [comment]
Please try https://asie.pl/files/UnlimitedChiselWorks-0.2.2-test1.jar

**Comment by asiekierka** [comment]
Once you've had some quality fun with the errors in -test1, please try https://asie.pl/files/UnlimitedChiselWorks-0.2.2-test2.jar

**Comment by asiekierka** [comment]
Filing this under "Mods doing silly things in 1.12+ that only are actually planned for in 1.14+ and thinking mods won't choke on them"
