### ISSUE TITLE
Ore Dictionary support?

### ISSUE THREAD

**Issue by katubug** [asiekierka/UnlimitedChiselWorks#48]
Hello! Firstly, thank you for the great mod! :D 

Would it be possible to add ore dictionary support? It seems none of the blocks have any oredict tags. Thank you!

Version: UnlimitedChiselWorks-0.2.1
Minecraft version: 1.12.2

**Comment by asiekierka** [comment]
Duplicate of #20, should be fixed by 0.3.3.
