### ISSUE TITLE
Metallurgy Crash On Load

### ISSUE THREAD

**Issue by JPitholz** [asiekierka/UnlimitedChiselWorks#49]
Adding Metallurgy 4: Reforged to a modpack with Unlimited Chiselworks

Crash Log: [pastebin](https://pastebin.com/k0htp2mA)

maximum id range exceeded?

Reproduceable : Yes

Only crashes on load when both are enabled.

**Comment by asiekierka** [comment]
Yep, you have too many blocks. Before 1.13.x, the game cannot have more than 4096 blocks registered. Get fewer mods, disable some functionality, or use something like JustEnoughIDs as a workaround.
