### ISSUE TITLE
Crash with UCW/Foamfix

### ISSUE THREAD

**Issue by AnsuzThurisaz** [asiekierka/UnlimitedChiselWorks#52]
You can find a log here: 
https://openeye.openmods.info/crashes/1cde15cef2fb88ace065c63d868f03f7

Along with others if you search openeye for cotm

**Comment by CritFlaw** [comment]
Having the same issue https://pastebin.com/0S5qQT3P

**Comment by Gamertech** [comment]
Same log and crash.

**Comment by thecrescentkid** [comment]
https://paste.dimdev.org/afotegihez.mccrash

**Comment by Slammyyyy** [comment]
Same issue, curiously enough it is seemingly random when it happens. On some startups I encounter 0 issues, others it will crash.

**Comment by pinipy** [comment]
https://pastebin.com/GJwpzKw3

Ive  had this server side and client side now. (Above is server side)

Also seems to be random! Sometimes my users get it, sometimes they dont

**Comment by Gamertech** [comment]
This is still an issue with 0.3.1

**Comment by asiekierka** [comment]
Was this fixed by UCW 0.3.2?

**Comment by AnsuzThurisaz** [comment]
Looks that way!

Thanks asie!

**Comment by Gamertech** [comment]
Yea, seems to be loading fine on 0.3.3 with smallPropertyStorage enabled.
