### ISSUE TITLE
[1.12.2] UCW broke with the latest Chisel Update.

### ISSUE THREAD

**Issue by Z-Tunic** [asiekierka/UnlimitedChiselWorks#54]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods:
Chisel-MC1.12.2-1.0.0.42
UnlimitedChiselWorks-0.2.4

-----

Was greeted to my base being redecorated by the Missing Textures Inc. I should stop entering their drawings for the free decorating that they offer if you win.

This is what it looks like in JEI and in the World they're missing textures with bits of text on them.
![](https://cdn.discordapp.com/attachments/377171551155650560/633407602147065856/chiselupdatebrokeUCW.PNG)

**Comment by asiekierka** [comment]
This might be rather difficult to fix, at least last time I tried to update to then-unreleased Chisel builds. Please be patient.

**Comment by asiekierka** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/110

**Comment by asiekierka** [comment]
^ was fixed. Far from the only problem. Please give me some time.

**Comment by Z-Tunic** [comment]
No rush. Take all the time you need.

**Comment by asiekierka** [comment]
Releasing 0.3.0 now. It might take a bit longer to load, as the loading code is not super optimized, but I'm not sure if I'll be able to dedicate enough time to fix this properly in the near future.
