### ISSUE TITLE
Crazy amount of missing textures

### ISSUE THREAD

**Issue by pinipy** [asiekierka/UnlimitedChiselWorks#56]
So I updated and there is a ridiculous amount of missing textures
![image](https://user-images.githubusercontent.com/56508897/69517203-bdfe5580-0f9f-11ea-8571-4bfa0d265ae2.png)

I'm talkin about 200 pages all up

**Comment by Markus292** [comment]
![2019-11-29_15 28 08](https://user-images.githubusercontent.com/58335594/69875427-645a9b80-12bd-11ea-8c07-1508561a55f0.png)
I just downloaded the newest version of the mod and i have a ton of missing textures too. Pls fix this as soon as possible.

**Comment by asiekierka** [comment]
https://asie.pl/files/UnlimitedChiselWorks-0.3.1-test2.jar Please try this

**Comment by Markus292** [comment]
Worked without any complication. Thank you and here have a whole back of Cookies and a great day/night

**Comment by asiekierka** [comment]
```
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.```

Well, you've got too many mods!
