### ISSUE TITLE
[request] Rockhounding Mod: Surface compatability

### ISSUE THREAD

**Issue by Glamdring804** [asiekierka/UnlimitedChiselWorks#57]
I was wondering if it would be possible to add support for the wood types from Rockhounding Mod: Surface.

https://www.curseforge.com/minecraft/mc-mods/rockhounding-mod-surface

I know your mod doesn't work so well with complicated textures, like the ones from Ceramics, so if this isn't feasible, please, by all means, delete the issue.

**Comment by asiekierka** [comment]
Why'd you close it?

**Comment by Glamdring804** [comment]
Because I realized that the only two woods the mod doesn't have native Chisel support for are the two with complicated textures, which will probably break your algorithm.
