### ISSUE TITLE
[Suggestion] Woods from Fossils and Archaeology and Spooky Biomes should be chiselable

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/UnlimitedChiselWorks#61]
Just what it says on the tin

**Comment by Sunconure11** [comment]
Side note, what exactly are you doing to pick up on modded blocks without having to install them to a workspace? Curious, since I want to do an addon that uses similar logic for rustic tables and chairs.

**Comment by asiekierka** [comment]
What do you mean exactly?

**Comment by Sunconure11** [comment]
Well, how are you avoiding having to install a bunch of dependencies in your workspace?

**Comment by asiekierka** [comment]
I'm only referring to blocks by their registry names - all the mod-specific "code" is in the JSONs in ucwdefs/, sans I think one exception in the code for Forestry/Binnie's Mods.

**Comment by Sunconure11** [comment]
Hm, maybe you could do the rustic addon then?

I’m not sure if a PR would work given the dev’s inactivity as of late.
