### ISSUE TITLE
Missing Texture After Chisel's new update on 3/28

### ISSUE THREAD

**Issue by BedrockLegends** [asiekierka/UnlimitedChiselWorks#68]
After updating both Chisel & Connected Textures mod for 1.12, Stuff like Planks and Bricks are missing Textures

**Comment by Z-Tunic** [comment]
I can confirm this as well.

Minecraft: 1.12.2
Forge: 14.23.5.2847

Chisel-MC1.12.2-1.0.2.45
CTM-MC1.12.2-1.0.2.31
UnlimitedChiselWorks-0.3.4

=====

Stone-like Seamless Double Slab, Plank-like Disarray Vertical, & Glass-like Brick Textures show up as a missing texture and if you attempt to place the block, they will convert into a different chisel'd block of the same type.

Blocks that get converted:
Stone-like Seamless Double Slab converts to Small Bricks.
Plank-like Disarray Vertical converts to Smooth.
Glass-like Brick converts to Panel.

**Comment by AJAdair110** [comment]
Yes, plank patterns are definitely broken.

**Comment by Ceifeire** [comment]
I see this is still an issue. Is there anyway to turn these textures off so they arent selectable?

**Comment by Z-Tunic** [comment]
Why was this issue close? This issue still exists unless there's a bugfix waiting?
