### ISSUE TITLE
Games fails to start and crash

### ISSUE THREAD

**Issue by Imrald** [asiekierka/UnlimitedChiselWorks#69]
The game fails to start and crash as in the title.
If i remove the mod the game start and load completely and i can play smoothly

Here's the crash report link
[https://pastebin.com/AManhgFP](url)
[https://pastebin.com/Tx5wuTsK](url)

**Comment by asiekierka** [comment]
You've added too much content to your modpack; Minecraft 1.12 has a limit of 4096 distinct block IDs. Either reduce the amount of
 content (f.e. by editing Unlimited Chisel Works's config file), or use a mod like JustEnoughIDs.
