### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Polyblock** [asiekierka/UnlimitedChiselWorks#7]
It's more a question than a bug report, are the blocks variants suppose to have chiseling recipe or does the mod only generate the blocks?

Using version 0.1.4 available on your website. 
![2017-09-24_11 32 45](https://user-images.githubusercontent.com/12652541/30784128-f3ce8048-a11c-11e7-8d9d-965114dcb6e9.png)

**Comment by asiekierka** [comment]
What Minecraft version are you using?

**Comment by Polyblock** [comment]
Oh sorry, forgot to say it. 1.12.1
