### ISSUE TITLE
[1.12.2] Broken UCW Chisel Patterns with Chisel-MC1.12.2-1.0.2.45

### ISSUE THREAD

**Issue by Z-Tunic** [asiekierka/UnlimitedChiselWorks#72]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Chisel-MC1.12.2-1.0.2.45
CTM-MC1.12.2-1.0.2.31
UnlimitedChiselWorks-0.3.4

=====

![](https://cdn.discordapp.com/attachments/377171551155650560/763819670913679400/ucwmissingtexturebug.PNG)
As of 'Chisel-MC1.12.2-1.0.2.45'... these chisel patterns from mods will show up as a missing texture in JEI as well as the iChisel's GUI. These are...

>Stone-like Seamless Double Slab
>Plank-like Disarray Vertical
>Glass-like Brick Textures

When you attempt to place these in the world, they get converted to a different type of chisel pattern, I assume the first in line if a invalid pattern is used. Here's what they get converted to...

>Stone-like Seamless Double Slab converts to Small Bricks.
>Plank-like Disarray Vertical converts to Smooth.
>Glass-like Brick converts to Panel.

I am aware that there was an issue opened about this already but... it was closed by the OP. I saw that there were no updates in the mod's source... so I'm opening this issue about it just in case. If by chance there's a patch arriving, this can be closed.

**Comment by Mofo50C** [comment]
ye i have the exact same issue its always seamless double slabs and disarray verticals

**Comment by Mofo50C** [comment]
has this mod died it'd be a shame :(
