### ISSUE TITLE
Game crash on startup please help 

### ISSUE THREAD

**Issue by KoRexGrind** [asiekierka/UnlimitedChiselWorks#73]
[crash-2021-01-13_03.03.46-client.txt](https://github.com/asiekierka/UnlimitedChiselWorks/files/5807227/crash-2021-01-13_03.03.46-client.txt)

**Comment by KoRexGrind** [comment]
Please help trying to fix my modpack.

**Comment by asiekierka** [comment]
You've added too much content to your modpack; Minecraft 1.12 has a limit of 4096 distinct block IDs. Either reduce the amount of content (f.e. by editing Unlimited Chisel Works's config file), or use a mod like JustEnoughIDs.
