### ISSUE TITLE
0.1.4 Version Triggers Update Notification for 0.1.4 Version

### ISSUE THREAD

**Issue by XvSkItZvX** [asiekierka/UnlimitedChiselWorks#8]
0.1.4 Version Triggers Update Notification for 0.1.4 Version

Not really much to say outside the title..shows a green dot on "mods" button and next to mod name in the list indicating and update.

**Comment by asiekierka** [comment]
Should be fixed in 0.1.5. Could you please verify?

**Comment by XvSkItZvX** [comment]
Confirmed, issue resolved. Thanks again!
